USE todo5lojavirtual; 
INSERT INTO tbprodutos
	(id_produto, nome_produto, descricao_produto, cod_categoria, quantidade, preco, tamanho, cor)
VALUES
	(DEFAULT,"BLUSA ALONGADA", "BLUSA ALONGADA EM TRICÔ COM ESTAMPA ANIMAL", "2", "10", "139", "PLUS SIZE", "MARROM"),
	(DEFAULT,"BLUSA ALONGADA2", "BLUSA ALONGADA EM TRICÔ COM ESTAMPA ANIMAL", "2", "10", "139", "PLUS SIZE", "PRETA"),
	(DEFAULT,"BLUSA TRICO P", "BLUSA CURTA EM TRICÔ CANELADO COM ABOTOAMENTO FRONTAL BEGE", "2", "5", "59.90", "P", "BRANCO"),
	(DEFAULT,"BLUSA TRICO M", "BLUSA CURTA EM TRICÔ CANELADO COM ABOTOAMENTO FRONTAL BEGE", "2", "5", "59.90", "M", "VERDE"),
	(DEFAULT,"BLUSA TRICO G", "BLUSA CURTA EM TRICÔ CANELADO COM ABOTOAMENTO FRONTAL BEGE", "2", "5", "59.90", "G", "AMARELO"),
	(DEFAULT,"CALÇA MOM P", "CALÇA MOM EM JEANS COM CINTO-LENÇO E BARRA DOBRADA BLUE JEANS", "2", "8", "159.90", "P", "AZUL"),
	(DEFAULT,"CALÇA MOM M", "CALÇA MOM EM JEANS COM CINTO-LENÇO E BARRA DOBRADA BLUE JEANS", "2", "8", "159.90", "M", "VERMELHO"),
	(DEFAULT,"CALÇA MOM G", "CALÇA MOM EM JEANS COM CINTO-LENÇO E BARRA DOBRADA BLUE JEANS", "2", "8", "159.90", "G", "BRANCO"),
	(DEFAULT,"CALÇA ANOS 90 G", "CALÇA ANOS 90 EM JEANS DESTROYED AZUL", "2", "5", "99.90", "P", "AZUL"),
	(DEFAULT,"JAQUETA JEANS P ", "JAQUETA TRUCKER EM JEANS COM BOLSOS AZUL", "3", "10", "199.90", "P", "AZUL"),
	(DEFAULT,"JAQUETA JEANS M ", "JAQUETA TRUCKER EM JEANS COM BOLSOS AZUL ESCURO", "3", "10", "199.90", "M", "PRETO"),
	(DEFAULT,"CAMISA BASICA M", "CAMISETA COMFORT EM ALGODÃO TEXTURIZADO MANGA LONGA PRETO", "3", "5", "70.90", "M", "PRETO"),
	(DEFAULT,"CAMISA BASICA G", "CAMISETA COMFORT EM ALGODÃO TEXTURIZADO MANGA LONGA PRETO", "3", "5", "70.90", "G", "PRETO"),
	(DEFAULT,"CALÇA INFANTIL EM MOLETOM", "CALÇA INFANTIL EM MOLETOM ESTAMPA CAMUFLADA COM BOLSOS EM ZÍPER - TAM 5 A 14 VERDE", "1", "12", "59.90", "TAM 05 A 14 ANOS", "VERDE"),
	(DEFAULT,"CALÇA INFANTIL EM MOLETOM", "CALÇA INFANTIL EM MOLETOM ESTAMPA CAMUFLADA COM BOLSOS EM ZÍPER - TAM 5 A 14 VERDE", "1", "12", "59.90", "TAM 05 A 14 ANOS", "VERDE");
    
select * from tbprodutos;